---
url: "http://localhost:8080/"
database: 
    host: "127.0.0.1"
    dbname: "nflix"
    user: "postgres"
    password: "qaninja"
users:
    cat_manager:
        login: "tony@stark.com"
        pass: "pwd123"